# Generated by Django 5.2.17 on 2026-09-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_achat', models.TextField(blank=True, null=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_activation', models.TextField()),
                ('produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Activation',
                'verbose_name_plural': 'Activations',
                'db_table': 'activation',
            },
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.CASCADE, related_name='prix_set', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Prix',
                'verbose_name_plural': 'Prix',
                'db_table': 'prix',
                'indexes': [models.Index(fields=['produit', 'is_active'], name='idx_prix_produit_active')],
            },
        ),
    ]
