# Generated by Django 5.2.17 on 2026-09-25 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'db_table': 'methode_paiement',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.RESTRICT, related_name='ventes', to='clients.client')),
                ('methode_paiement', models.ForeignKey(db_column='id_methode_paiement', on_delete=django.db.models.deletion.RESTRICT, related_name='ventes', to='sales.methodepaiement')),
                ('user_affilie', models.ForeignKey(db_column='id_user_affilie', on_delete=django.db.models.deletion.RESTRICT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'vente',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(db_column='id_produit', on_delete=django.db.models.deletion.RESTRICT, related_name='commandes', to='catalog.produit')),
                ('vente', models.ForeignKey(db_column='id_vente', on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='sales.vente')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'commande',
            },
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['date'], name='idx_vente_date'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['client'], name='idx_vente_client'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['user_affilie'], name='idx_vente_user'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['methode_paiement'], name='idx_vente_paiement'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['vente'], name='idx_commande_vente'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['produit'], name='idx_commande_produit'),
        ),
    ]
