# Generated by Django 5.2.17 on 2026-09-25 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
