# Generated by Django 5.2.17 on 2026-09-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0002_alter_commande_date_alter_vente_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaBuyerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_pub', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Coût de publicité (Ar)')),
                ('regle_ca', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Taux com sur CA si marge > seuil (%)')),
                ('regle_benefice', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Taux com sur Bénéfice si marge <= seuil (%)')),
                ('seuil_marge', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='Seuil de marge bénéficiaire (%)')),
                ('base_recouvrement', models.CharField(choices=[('benefice', 'Bénéfice brut'), ('ca', "Chiffre d'affaires")], default='benefice', max_length=20, verbose_name='Base de recouvrement du coût pub')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provenances', models.ManyToManyField(blank=True, related_name='media_buyer_commissions', to='clients.provenance', verbose_name='Provenances éligibles')),
            ],
            options={
                'verbose_name': 'Commission Media Buyer',
                'verbose_name_plural': 'Commissions Media Buyer',
                'db_table': 'media_buyer_commission',
            },
        ),
    ]
