# Generated by Django 5.2.17 on 2026-09-29 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0003_mediabuyercommission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='numero_commande_fournisseur',
            field=models.CharField(blank=True, db_column='numero_commande_fournisseur', max_length=100, null=True, verbose_name='Numéro de commande fournisseur'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['numero_commande_fournisseur'], name='idx_vente_num_cmd_fourn'),
        ),
    ]
