# Generated by Django 5.2.17 on 2026-09-30 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0004_vente_numero_commande_fournisseur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du fournisseur')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact / Référence')),
                ('site_web', models.CharField(blank=True, max_length=500, null=True, verbose_name='Site web / Lien portail')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Informations')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='fournisseur',
            field=models.ForeignKey(blank=True, db_column='id_fournisseur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='sales.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['fournisseur'], name='idx_vente_fournisseur'),
        ),
    ]
